logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    space.nixus: DEBUG
  main:
    banner-mode: off
  security:
    filter:
      order: 10
  cloud:
    gcp:
      datastore:
        namespace: micro-services
      project-id: micro-services-378415
space:
  nixus:
    pubtrans:
      challenge-minutes: 2
      issuer: space.nixus.micro-services-378415
      expiry-minutes: 120
